# Generated by Django 5.2.4 on 2025-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_tag_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField()),
                ("rate", models.IntegerField()),
                ("date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="user.specification"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="user.review"
            ),
        ),
    ]
