# Generated by Django 5.2.4 on 2025-07-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="images",
        ),
        migrations.DeleteModel(
            name="BasketItem",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Specification",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="SaleItem",
        ),
    ]
