services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: online_shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./online_shop:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: shop-network
