# Generated by Django 5.2.4 on 2025-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
