# Generated by Django 5.2.4 on 2025-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_basketitem_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "express_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=10,
                        verbose_name="Экспресс-доставка ",
                    ),
                ),
                (
                    "regular_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=200,
                        max_digits=10,
                        verbose_name="Обычная доставка ",
                    ),
                ),
                (
                    "free_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        max_digits=10,
                        verbose_name="Бесплатная доставка от ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки доставки",
                "verbose_name_plural": "Настройки доставки",
            },
        ),
    ]
