# Generated by Django 5.2.4 on 2025-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_deliverysettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverysettings",
            options={
                "verbose_name": "Delivery settings",
                "verbose_name_plural": "Delivery settings",
            },
        ),
        migrations.AlterField(
            model_name="deliverysettings",
            name="express_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                max_digits=10,
                verbose_name="Express delivery",
            ),
        ),
        migrations.AlterField(
            model_name="deliverysettings",
            name="free_from",
            field=models.DecimalField(
                decimal_places=2,
                default=2000,
                max_digits=10,
                verbose_name="Free delivery from",
            ),
        ),
        migrations.AlterField(
            model_name="deliverysettings",
            name="regular_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=200,
                max_digits=10,
                verbose_name="Regular delivery",
            ),
        ),
    ]
