# Generated by Django 5.2.4 on 2025-10-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_deliverysettings_options_and_more"),
        ("product", "0008_rename_price_product_standart_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="basketitem",
            index=models.Index(fields=["user"], name="order_baske_user_id_366cae_idx"),
        ),
        migrations.AddIndex(
            model_name="basketitem",
            index=models.Index(
                fields=["product"], name="order_baske_product_d8e0dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="order_order_user_id_a7f1ea_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["createdAt"], name="order_order_created_6c31e2_idx"
            ),
        ),
    ]
