# Generated by Django 5.2.4 on 2025-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_orderitem_alter_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
