# Generated by Django 5.2.4 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="order.orderitem"),
        ),
    ]
