# Generated by Django 5.2.4 on 2025-10-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverysettings",
            options={
                "verbose_name": "Delivery settings",
                "verbose_name_plural": "Delivery's settings",
            },
        ),
    ]
