# Generated by Django 5.2.4 on 2025-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("user", "0009_remove_order_products_remove_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                related_name="product_images", to="user.image"
            ),
        ),
    ]
