# Generated by Django 5.2.4 on 2025-07-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="images",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="title",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
