# Generated by Django 5.2.4 on 2025-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0003_remove_saleitem_images_remove_saleitem_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limitedEdition",
            field=models.BooleanField(default=False),
        ),
    ]
