# Generated by Django 5.2.4 on 2025-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_limitededition"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count_of_sales",
            field=models.IntegerField(default=0),
        ),
    ]
