# Generated by Django 5.2.4 on 2025-07-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_count_of_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sort_index",
            field=models.IntegerField(default=0),
        ),
    ]
