# Generated by Django 5.2.4 on 2025-07-24 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_sort_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count_of_sales",
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
