# Generated by Django 5.2.4 on 2025-07-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_product_count_of_sales_alter_product_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="standart_price",
        ),
    ]
