# Generated by Django 5.2.4 on 2025-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_price_product_standart_price"),
        ("user", "0009_remove_order_products_remove_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent"], name="product_cat_parent__b54811_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="product_pro_categor_2b9d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="product_pro_title_07e491_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sort_index"], name="product_pro_sort_in_628f0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rate"], name="product_rev_rate_4a14d2_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["product"], name="product_sal_product_179593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="product_tag_name_bf4b57_idx"),
        ),
    ]
